# Server build configuration
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npx prisma generate && npm run build"]

[start]
cmd = "npx prisma db push && npm start"
